
import LocalizedStrings from 'react-native-localization';
module.exports =  new LocalizedStrings({
en:{
  Lang : "en",
  Login : "Login",
  Email : "Email",
  Password : "Password",
  Forgot : "Forgot?",
  NotMember : "Not a member yet?",
  Register : "Register",
  FillEmail	: "Fill in the email and password you used to register.",
  Error : "Internet Error",
  EightChar : "Passwords must be at least 8 characters",
  LoginFail : "Login Fail: unregistered email or wrong password.",
  Rewards : "Rewards",
  Referral : "Referral",
  History : "History",
  Copy : "Copy",
  Yes : "Yes",
  No : "No",
  Logout : "Logout",
  Wantlogout : "Do you want to logout?",
  Receive : "Receive",
  Name : "Name",
  Confirm : "Confirm Password",
  Cancel : "Cancel",
  NoMatch : "Passwords don't match",
  FillAll : "Please fill in all fields",
  EightChar	: "Passwords must be at least 8 characters",
  Send : "Send",
  Amount : "Amount",
  Memo : "Memo",
  Receiver : "Receiver Email",
  ExitApp :	"Exit App?",
  Exit : "Exit",
  Click	: "Click 'Yes' to exit",
  Refresh : "Refresh...",
  NoConnection : "No connection to Server!",
  Unexpected : "Unexpected Error! Please login again.",
  EmailAmount : "Please enter email and amount to transfer",
  Wait : "Wait...",
  NotEnough : "Not enough to transfer!",
  ConfirmTransfer	: "Confirm transfer to",
  Confirm	: "Confirm",
  Success : "Transfer Successful",
  Alert : "Alert",
  Logs : "Transfer Logs",
  Ok : 'OK',
  Wait : "Please wait..",
  Norecords : "No Records",
},
zh: {
  Lang : "zh",
  Login : "登录",
  Email : "电邮",
  Password : "密码",
  Forgot : "忘记密码？",
  NotMember : "非会员？ 请注册。",
  Register : "注册",
  FillEmail	: "填写您用于注册的电子邮件和密码。",
  Error : "内部错误",
  EightChar : "密码必须至少包含八个字符",
  LoginFail : "登录失败-未注册的电子邮件或错误的密码。",
  Rewards : "奖励",
  Referral : "推荐",
  History : "转移日志",
  Copy : "拷贝",
  Yes : "是",
  No : "不是",
  Logout : "登出",
  Wantlogout : "你想登出吗？",
  Receive : "接收",
  Name : "名字",
  Confirm : "确认密码",
  Cancel : "取消",
  NoMatch : "确认密码不一样。",
  FillAll : "请填写所有字段",
  EightChar	: "密码必须至少包含八个字符",
  Send : "发送",
  Amount : "量",
  Memo : "备忘录",
  Receiver : "收件人的电子邮件",
  ExitApp :	"退出 ?",
  Exit : "退出",
  Click	: "点击 '是' 退出",
  Refresh : "刷新...",
  NoConnection : "没有连接到服务器！",
  Unexpected : "无法预料的错误！ 请再次登录。",
  EmailAmount : "请输入电子邮件和转移金额。",
  Wait : "请稍候...",
  NotEnough : "不足以转移！",
  ConfirmTransfer	: "确认转移到",
  Confirm	: "确认",
  Success : "转移成功",
  Alert : "警报",
  Logs : "转移日志",
  Ok : "好",
  Wait : "请稍候..",
  Norecords : "没有记录"
}
});
